### ISSUE TITLE
Recent showcase additions not showing on live site

### ISSUE THREAD

**Issue by davemullenjnr** [planetjekyll/showcase#17]
I've just submitted my Jekyll-based site and you kindly merged my pull request. Just looking at both the most recently merged pull requests and the [showcase](http://planetjekyll.github.io/showcase/) page, it would seem that the latest additions are not being compiled to the live site.

Perhaps i'm missing something but just thought i'd mention it.

Thanks,
Dave.

**Comment by geraldb** [comment]
I know. Sorry for now it's not automatic - the publishing needs another manual build step. Thanks for your patience. Cheers. Prost.

**Comment by davemullenjnr** [comment]
Hi Prost. That's no problem and thanks for letting me know. :)
